version: '3.4'

services:
  mongo:
    container_name: expenses-mongodb
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=expensesadmin01!
      - MONGO_INITDB_DATABASE=expenses-db
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db

volumes: 
  mongo: